##########################################################################
name: ArchLinux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: Download Packages
        run: |
          LC_ALL=C pacman-V| sed -r 's#[0-9]+#543#g' |md5sum|cut c1-6
