##########################################################################
name: ArchLinux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: RUN
        run: |
         pacman -Syu sudo go git curl wget base-devel linux-firmware --noconfirm
         useradd -m tmp
         echo "tmp ALL=(ALL) NOPASSD: ALL" >> /etc/sudoers
         su - tmp
         git clone https://aur.archlinux.org/yay.git
         cd yay
         makepkg -si --noconfirm
         yay linux-xanmod-edge --noanswerdiff
         yay linux-xanmod-edge-headers --noanswerdiff
         
         - name: Upload a Build Artifact
           uses: actions/upload-artifact@v2.3.1
           with:
               name: linux-xanmod-edge
               path: ~/.cache/yay/linux-xanmod-edge/*.pkg.tar.zst
         
         - name: Upload a Build Artifact
           uses: actions/upload-artifact@v2.3.1
           with:
               name: linux-xanmod-edge
               path: ~/.cache/yay/linux-xanmod-edge-headers/*.pkg.tar.zst
