##########################################################################
name: ArchLinux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: Install depends
        run: pacman -Syu sudo go git curl wget base-devel linux-atm linux linux-firmware bc base --noconfirm
         
      - name: Preparing Source 
        run: |
             wget https://github.com/xanmod/linux/archive/5.15.17-xanmod2-tt.tar.gz 
             tar -xf 5.15.17-xanmod2-tt.tar.gz
             mv .config linux-5.15.17-xanmod2-tt
             
      - name: Build
        run: |
             cd linux-5.15.17-xanmod2-tt
             make 
             ls
             
      - name: Upload
        uses: actions/upload-artifact@v2.3.1
        with:
           name: BUILD
           path: linux-5.15.17-xanmod2-tt
