##########################################################################
name: ArchLinux

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: Download Packages
        run: |
          pacman -Scc --noconfirm
          pacman -Syyyu rsync base base-devel linux linux-firmware linux-atm ngrok mc intel-ucode amd-ucode xorg xorg-server gnome gdm grub os-prober ntfs-3g sudo nano mc curl wget git openssh openssl neofetch zsh gpart gparted --noconfirm
          mkdir ~/pacman
          rsync -r /var/cache/pacman/pkg/* ~/pacman/
          repo-add -R ~/pacman/Local.db.tar.gz ~/pacman/*.tar.zst
          repo-add -R ~/pacman/Local.db.tar.gz ~/pacman/*.tar.xz

      - name: Upload Pacman Package
        uses: actions/upload-artifact@v2
        with:
            name: Package
            path: pacman/*
            if-no-files-found: error
