##########################################################################
name: ArchLinux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
      #image: archlinux
      #options: --privileged
      #volumes:
        #- /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################

      - name: Running Script
        run: PACKAGES="live-build"

      - name: update
        run: apt update
      - name: Download
        run: apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends ${PACKAGES} | grep "^\w")   
      - name: ls
        run: ls
        
